apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mydb1
  name: mydb1
  namespace: simplilearn-project7
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mydb1
  type: ClusterIP
status:
  loadBalancer: {}
