apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: simplilearn-project7
  creationTimestamp: null
  labels:
    app: wp
  name: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wp
    spec:
      containers:
      - image: docker.io/wordpress
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mydb1
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              key: myusername
              name: envcm
        - name: WORDPRESS_DB_PASSWORD
          value: simplilearn
        - name: WORDPRESS_DB_NAME
          value: niit
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wpclaim
      initContainers:
      - name: init-mydb1
        image: docker.io/mysql:5.7
        command: ['sh', '-c', 'until getent hosts mydb1; do echo waiting for mydb1; sleep 2; done;']
