apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wp
  name: wp
  namespace: simplilearn-project7
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wp
  type: NodePort
status:
  loadBalancer: {}
